version: 2.1
executors:
  docker-publisher:
    working_directory: ~/iris
    environment: 
      IMAGE_NAME: rsutton/iris 
    docker:
      - image: docker:17.05.0-ce-git
jobs:
  developer:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build . -t $IMAGE_NAME:${CIRCLE_SHA1}
      - run: docker run -d --rm --name iris -p 8000:8000 $IMAGE_NAME:${CIRCLE_SHA1}
      - run: docker exec -t iris python -m unittest discover -s iris/tests

  build:
    executor: docker-publisher
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build latest
          command: docker build . -t $IMAGE_NAME:latest
      - run:
          name: Build tagged
          command: docker build . -t $IMAGE_NAME:${CIRCLE_TAG}
      - run:
          name: Archive image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: ~/iris
          paths:
            - ./image.tar

  test:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Load archived image
          command: docker load -i image.tar
      - run: docker run -d --rm --name iris -p 8000:8000 $IMAGE_NAME
      - run: docker exec -t iris python -m unittest discover -s iris/tests

  publish:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Load archived image
          command: docker load -i image.tar
      - run:
          name: Publish to Docker Hub
          command: |
            echo "${DOCKERHUB_PASS}" | docker login -u "${DOCKERHUB_USER}" --password-stdin
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:${CIRCLE_TAG}

workflows:
  version: 2.1
  developer:
    jobs:
      - dev
  build_test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/  
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/ 
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/            

