version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.7.6
    steps:
      - checkout
      # - setup_remote_docker
      # build the application image
      - run: docker build -t rsutton/iris:$CIRCLE_BRANCH .
      # save the image
      # - run: docker push rsutton/iris:$CIRCLE_BRANCH
      # run the app
      - run: |
          docker run -d --name iris -p 8000:8000 rsutton/iris:$CIRCLE_BRANCH
      - run: |
          status=$(curl -s -X POST http://localhost:8000/api/v1/predict?sepal_length=1&sepal_width=1&petal_length=1&petal_width=1 |
          jq -r '.prediction')
          if [ "$status" != "1" ]; then
            echo "Prediction error: expected 1 got $status"
            exit 1
          fi
      - run: |
          docker stop -d --name iris 

