version: 2

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t rsutton/iris:$CIRCLE_SHA1 .
      - run: docker run -d --rm --name iris -p 8000:8000 rsutton/iris:$CIRCLE_SHA1
      - run: docker exec -it iris python -m unittest discover -s iris/tests
      - run: docker stop iris
