name: Build Docker 
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
        name: Build the Docker Image
        run: docker build . --file Dockerfile --tag rsutton/iris:$GITHUB_REF
        