name: Build Docker 
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test Docker Image
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build 
      run: docker build . --file Dockerfile --tag rsutton/iris:$GITHUB_SHA
    - name: Run  
      run: docker run -d --rm --name iris -p 8000:8000 rsutton/iris:$GITHUB_SHA
    - name: Test
      run: docker exec -t iris python -m unittest discover -s iris/tests
